# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Neeraj Sewani
title: Android and MERN Stack Web developer
email: neerajsewanisrt8@gmail.com
# phone: Your phone number (optional)
# website: Your website (eg. https://google.com)(optional)

# Social links
# twitter_username: jekyllrb
github_username:  neer17
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# Its stackoverflow
instagram_username: users/7379765/neer17  
linkedin_username: neeraj-sewani-721a39b7
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: ./../images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Started my programming journey as an Android developer two years ago and now from last six
  months developing apps following the best practices of Android like using Jetpack
  and Kotlin for coding. Moreover, in parallel to Android apps 
  I have been learning and developing Web apps in MERN stack from last one and a half years.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Apart from working on my core areas I dedicate my sundays on exploring new
  programming languages and technologies. And apart from tech I
  recently discovered my interest in nutrition and fitness.  

# Footer
# footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]